# Generated by Django 3.2.4 on 2021-07-03 12:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_submission_submission_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='submission_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 3, 12, 53, 19, 718827)),
        ),
    ]
